- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/setup_15.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install essential packages
  apt:
    pkg:
      - python3
      - tar
      - gzip
      - nodejs
    state: present

- name: Install pm2
  shell: npm install pm2 -g

- name: Configure environment variable
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: ${TYPEORM_HOST}
    TYPEORM_PORT: ${TYPEORM_PORT}
    TYPEORM_USERNAME: ${TYPEORM_USERNAME}
    TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
    TYPEORM_DATABASE: ${TYPEORM_DATABASE}