- name: "Create directory"
  become_user: ubuntu
  file:
    path: ~/udapeople/
    state: directory

- name: "deploy backend"
  become_user: ubuntu
  unarchive:
    src: /etc/app.tar.gz
    dest: ~/udapeople/

- name: "run backend"
  become_user: ubuntu
  shell: |
    cd ~/udapeople/
    npm i    
    pm2 start npm -- run start