- name: "Create directory"
  become_user: ubuntu
  shell: mkdir -p ~/udapeople/

- name: "deploy backend"
  become_user: ubuntu
  unarchive:
    src: /etc/udapeople/app.tar.gz
    dest: ~/udapeople/

- name: "run backend"
  become_user: ubuntu
  shell: |
    cd ~/udapeople/
    npm i    
    pm2 start main.js