- name: "deploy backend"
  copy:
    src: ~/project/backend/dist/
    dest: /etc/udapeople/
    remote_src: yes

- name: "run backend"
  shell: |
    cd /etc/udapeople/
    npm i    
    pm2 start main.js --update-env