- name: "deploy backend"
  copy:
    src: ~/project/backend/
    dest: ~/udapeople/
    remote_src: yes

- name: "run backend"
  shell: |
    cd ~/udapeople/
    npm i    
    pm2 start main.js --update-env