ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
ANSIBLE_HOST_KEY_CHECKING: False
ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}"
CIRCLE_WORKFLOW_ID: "{{ lookup('env','CIRCLE_WORKFLOW_ID') }}"
TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"